opt_in_rules:
    - force_unwrapping
    - opening_brace

force_unwrapping:
    severity: error

trailing_whitespace:
    severity: error

identifier_name:
    excluded:
        - id
        - ok

type_name:
    allowed_symbols:
        - _TupleContent
        - _OptionalContent
        - _ConditionalContent
        - _EncodablePayload
        - _DataPayload
        - _DictionaryPayload
        - _StringPayload
