name: Documentation

on:
  workflow_dispatch:
  release:
    types:
      - published

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  documentation:
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: request-dl/.github/.github/workflows/documentation.yml@main
    with:
      swift-version: 5.7.2
      target: RequestDL
      hosting-base-path: request-dl
      output: ./_site
    secrets: inherit
