name: Swiftlint

on:
  push:
     branches:
     - main
  pull_request:

jobs:
  lint:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Install swiftlint
        run: >
          if [[ ! -f "/usr/local/bin/swiftlint" ]]
             then
               brew install swiftlint
             fi

      - name: Swiftlint
        run: swiftlint lint
