name: No API Breaking Changes

on:
  pull_request:
    branches: [main]
    paths:
      - 'Package.swift'
      - 'Sources/**'
      - '.github/workflows/no-breaking-changes.yml'

jobs:
  breaking-changes:
    uses: request-dl/.github/.github/workflows/no-breaking-changes.yml@no-api-breaking-changes
    with:
      swift-version: 5.7.2
      platform: macOS-latest
    secrets: inherit
