name: Swift

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["5.8", "5.7"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: ☑️ Swift Select
        uses: swift-actions/setup-swift@v1
        with:
            swift-version: ${{ matrix.swift }}

      - name: ⬇️ Get Sources
        uses: actions/checkout@v3.3.0

      - name: 🍀 Test Package
        run: swift test
