name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: macOS-latest
    steps:
      - name: OpenSSL Update
        run: |
            brew upgrade openssl

      - name: Xcode Select
        uses: devbotsxyz/xcode-select@v1.1.0
        with:
          version: 14.0.1

      - name: Get Sources
        uses: actions/checkout@v3.3.0

      - name: Build Package
        run: swift build -v

      - name: Test & publish code coverage to Code Climate
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: swift test --enable-code-coverage
          debug: true
          coverageLocations: ${{github.workspace}}/.build/debug/codecov/*.json:lcov-json
