name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: macOS-latest
    steps:
      - name: ☑️ Xcode Select
        uses: maxim-lobanov/setup-xcode@v1.5.1
        with:
          xcode-version: 14.0.1

      - name: ⬇️ Get Sources
        uses: actions/checkout@v3.3.0

      - name: 🛠️ Build Package
        run: swift build -v

      - name: 🍀 Code Coverage (Code Climate)
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: swift test --enable-code-coverage
          debug: true
          coverageLocations: ${{github.workspace}}/.build/debug/codecov/*.json:lcov-json
